on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ignisda/developrs/packages/cinder/action
        with:
          cinder-endpoint: 'http://cinder.ignisda.tech'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "Affected projects ${{ steps.hello.outputs.affected }}"
